### ISSUE TITLE
...

### ISSUE THREAD

**Issue by TonyDroidd** [iksaku/InventoryBlocker#1]
Now work's?

**Comment by iksaku** [comment]
Aún no xD espera y yo te avisaré cuándo funcione ;) tal vez tarde unos días, tendré qué viajar de imprevisto a Chihuahua esta semana xD =

**Comment by TonyDroidd** [comment]
Sale pues xD

**Comment by TonyDroidd** [comment]
Now?

**Comment by iksaku** [comment]
Nope... Please wait a few more days, I'm not at home xD

**Comment by ghost** [comment]
Yey gente que habla español Tony soy sub
